package com.example.bestcrmintheuniverse.entities;
import com.example.bestcrmintheuniverse.entities.ContactPoint;
import jakarta.persistence.*;
@Entity
public class Deal {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @Column(name = "id", nullable = false)
    private Long id;

    private Double budget;
    private String email;
    private String phone;

    @ManyToOne
    @JoinColumn(name = "client_id")
    private Client client;

    @ManyToOne
    @JoinColumn(name = "contact_point_id")
    private ContactPoint contactPoint;

    public Deal() {
    }

    // Getters and setters

    public Long getId() {
        return id;
    }

    // No need to set the ID manually, as it will be generated by the database

    public Double getBudget() {
        return budget;
    }

    public void setBudget(Double budget) {
        this.budget = budget;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public Client getClient() {
        return client;
    }

    public void setClient(Client client) {
        this.client = client;
    }

    public ContactPoint getContactPoint() {
        return contactPoint;
    }

    public void setContactPoint(ContactPoint contactPoint) {
        this.contactPoint = contactPoint;
    }

}