package com.example.bestcrmintheuniverse.entities;

import jakarta.persistence.*;

import java.util.Date;

@Entity
public class Person {
    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE)
    @Column(name = "id", nullable = false)
    private Long id;

    @ManyToOne
    private Client client;

    private String name;
    private String address;
    private String phone;
    private String email;

    @Temporal(TemporalType.TIMESTAMP)
    private Date lastContact;

    // Constructors, getters, and setters

    public Long getId() {
        return id;
    }

    // No need to set the ID manually, as it will be generated by the database
}
